### ISSUE TITLE
bash: ./bbb-mp4-bulk-parallel.sh: No such file or directory

### ISSUE THREAD

**Issue by djoudi** [manishkatyan/bbb-mp4-old#4]
root@live:~/bbb-mp4# ./bbb-mp4-bulk-parallel.sh
bash: ./bbb-mp4-bulk-parallel.sh: No such file or directory

**Comment by manishkatyan** [comment]
You may want to use the simpler version: node bbb-mp4.js <recording-id>
Above will convert the given recording into MP4.
