### ISSUE TITLE
bash: ./bbb-mp4-bulk-parallel-input-file.sh: No such file or directory

### ISSUE THREAD

**Issue by djoudi** [manishkatyan/bbb-mp4-old#5]
root@live:~/bbb-mp4# ./bbb-mp4-bulk-parallel-input-file.sh
bash: ./bbb-mp4-bulk-parallel-input-file.sh: No such file or directory

**Comment by manishkatyan** [comment]
Above script expects list of recordings that you want to convert into MP4. Looks like you have not created such a file. 

You may want to use the simpler version: node bbb-mp4.js <recording-id>
Above will convert the given recording into MP4.
